### ISSUE TITLE
emuglGLESv2_enc: device/MTL/opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2305 GL error 0x501

### ISSUE THREAD

**Issue by 12321321321-hue** [wenii/EGLDemo#2]
emuglGLESv2_enc: device/MTL/opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2305 GL error 0x501

**Comment by wenii** [comment]
你这个是怎么出现的？我用Android studio编译没问题哈。

**Comment by 12321321321-hue** [comment]
首先十分感谢您的回复，估计是配置的问题，后面我添加了一些配置就可以编译了，这个项目让我学习到了很多，非常感谢，不过有一个疑难的问题，我在您的项目中没有看到，如果您不嫌麻烦，能否加个q呢&nbsp; 1014909632，关于缩放之后平移的问题，超出屏幕；打扰您了，还是再次感谢您哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wenii/EGLDemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 凌晨0:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wenii/EGLDemo] emuglGLESv2_enc: device/MTL/opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetUniformLocation:2305 GL error 0x501 (Issue #2)





 
你这个是怎么出现的？我用Android studio编译没问题哈。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
